### ISSUE TITLE
KCP_EXTRA_ARGS参数怎么设定，比如mtu, rcvwnd, sndwnd等

### ISSUE THREAD

**Issue by gujia9999** [chenhw2/Dockers#1]
怎么输入指令。。。不会用docker。。。真是捉急啊

**Comment by honwen** [comment]
只支持mode, crypt, key三个参数。更多的。。。懒得写

**Comment by gujia9999** [comment]
用了几个docker只有你这个特别好！ 强烈建议添加rcvwnd, sndwnd这两项，默认值速度大打折扣。。。如果能有 datashard, sndwnd, dscp，mtu这几项的话就更好了

**Comment by honwen** [comment]
好久没用，看一眼其实是留了参数```KCP_EXTRA_ARGS```的，将mtu, rcvwnd, sndwnd等写入```KCP_EXTRA_ARGS```就行。

Example: ```-e KCP_EXTRA_ARGS="-nocomp -mode manual -nodelay 1 -resend 1 -nc 1 -interval 10"```

**Comment by gujia9999** [comment]
试了一下你说的，没成功。。显示参数设置有误

**Comment by honwen** [comment]
Test OK with:
```
docker run -d \
    -e "SSR=ssr://origin:chacha20-ietf:http_post_compatible:12345678" \
    -e "KCP_EXTRA_ARGS=--parityshard 9 --sndwnd 512 --dscp 3 --mtu 1122" \
    -p 8388:8388/tcp -p 8388:8388/udp -p 18388:18388/udp \
    chenhw2/ssr-kcp-server
```
