### ISSUE TITLE
Can you customize "SSR" and "kcptun" ports?

### ISSUE THREAD

**Issue by github9751** [chenhw2/Dockers#2]
docker pull chenhw2/ssr-kcp-server
I tried it. Customization is not acceptable.
-p 8388:8388/tcp -p 8388:8388/udp -p 18388:18388/udp
好像端口写死了 。。。      SSR(:@) and KCP(-l -t )参数不起作用
Best regards

**Comment by honwen** [comment]
-p [你要的SSR端口]:8388/tcp -p [你要的SSR端口]:8388/udp -p [你要的KCP端口]:18388/udp

**Comment by github9751** [comment]
Although the backstage looks like this →/ssr/kcptun/server -t 127.0.0.1:8388 -l :18388
I did what you said, and everything worked well.Best regards
